import MyGUI
from MyLists import List
from Institution import Club, School, Kindergarten, OtherInst


c1 = Club("Гурток1", 250, "Тижнева", 0, "футбол")
c2 = Club("Гурток2", 15, "Місячна", 1, "волейбол")
c3 = Club("Гурток3", 20, "Денна", 2, "живопис")
c4 = Club("Гурток4", 10, "Місячна", 3, "музична школа")
s1 = School("Школа1", 120, "Річна", 4)
s2 = School("Школа2", 20, "Денна", 5)
s3 = School("Школа3", 50, "Тижнева", 6)
s4 = School("Школа4", 75, "Тижнева", 7)
k1 = Kindergarten("Дитячий садок1", 200, "Місячна", 8)
k2 = Kindergarten("Дитячий садок2", 10, "Денна", 9)
k3 = Kindergarten("Дитячий садок3", 2000, "Річна", 10, )
k4 = Kindergarten("Дитячий садок4", 50, "Тижнева", 11)
o1 = OtherInst("Інше1", 250, "Місячна", 12, "курс по програмуванню")
o2 = OtherInst("Інше2", 105, "Місячна", 13, "автошкола")
o3 = OtherInst("Інше3", 45, "Тижнева", 14, "репетитор з англійської")
o4 = OtherInst("Інше4", 10, "Денна", 15, "автошкола2")
lis = List()
lis.add_inst(c1)
lis.add_inst(c2)
lis.add_inst(c3)
lis.add_inst(c4)
lis.add_inst(s1)
lis.add_inst(s2)
lis.add_inst(s3)
lis.add_inst(s4)
lis.add_inst(k1)
lis.add_inst(k2)
lis.add_inst(k3)
lis.add_inst(k4)
lis.add_inst(o1)
lis.add_inst(o2)
lis.add_inst(o3)
lis.add_inst(o4)
a = MyGUI.GUI(lis)
a.start()
